PildorasBlog/PildorasBlog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('servicios/', include('serviciosApp.urls')),
    path('blog/', include('blog_app.urls')),
    path('contacto/', include('contacto_app.urls')),
    path('tienda/', include('tienda.urls')),
    path('carro/', include('carro_compras.urls')),
    path('autenticacion/', include('autenticacion.urls')),
    path('pedidos/', include('pedidos.urls')),
    path('', include('BlogApp.urls')),
]

PildorasBlog/carro_compras/urls.py
from django.urls import path
from . import views

app_name="carro"

urlpatterns = [
    path('agregar/<int:producto_id>/', views.agregar_producto, name="agregar"),
    path('eliminar/<int:producto_id>/', views.eliminar_producto, name="eliminar"),
    path('restar/<int:producto_id>/',views.restar_producto, name="restar"),
    path('limpiar/',views.limpiar_carro, name="limpiar"),
]

PildorasBlog/tienda/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.tienda_view, name='tienda'),
]

PildorasBlog/tienda/models.py
from http.client import PRECONDITION_FAILED
from tabnanny import verbose
from tkinter import CASCADE, image_names
from django.db import models
from django.forms import CharField

# Create your models here.

class CategoriaProducto(models.Model):
    nombre=models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
    class Meta:
        verbose_name="CategoriaProd"
        verbose_name_plural="CategoriasProd"

    def __str__(self) :
        return self.nombre

class Producto(models.Model):
    nombre = models.CharField(max_length=60)
    categorias= models.ForeignKey(CategoriaProducto, on_delete=models.CASCADE)
    imagen= models.ImageField(upload_to="tienda", null=True, blank=True)
    precio = models.FloatField()
    disponibilidad= models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
    class Meta():
        verbose_name = "Producto"
        verbose_name_plural = "Productos"

    def __str__(self) :
        return self.nombre

PildorasBlog/tienda/views.py
from django.shortcuts import render
from .models import Producto

# Create your views here.

def tienda_view(request):
    producto = Producto.objects.all()

    context={
        "productos": producto
    }
    return render (request, "app/tienda.html", context)

PildorasBlog/tienda/templates/carro/widget.html
<table
  class="table table-bordered"
  style="color: white; background-color: rgb(6, 51, 6); margin-top: 20px"
>
  <thead>
    <tr>
      <th colspan="3" class="text-center">Carro compras</th>
    </tr>
    <tr>
      <th>Producto</th>
      <th>Cantidad</th>
      <th>Suma</th>
    </tr>
  </thead>

  <tbody>
    {% if request.session.carro.items %}
    <br />
    {% for key, value in request.session.carro.items %}
    <tr class="text-center">
      <td>{{value.producto_nombre}}</td>
      <td>{{value.producto_cantidad}}</td>
      <td>
        <a
          href="{% url 'carro:agregar' value.producto_id %}"
          class="btn btn-sm btn-success"
          >+</a
        >
        <a
          href="{% url 'carro:restar' value.producto_id %}"
          class="btn btn-sm btn-success"
          >-</a
        >
        <a
          href="{% url 'carro:eliminar' value.producto_id %}"
          class="btn btn-sm btn-danger"
          >x</a
        >
        {{value.producto_precio}} $
      </td>
    </tr>
    {% endfor %}
    <tr class="text-center">
      <td colspan="3">
        <a href="{% url 'carro:limpiar' %}" class="btn btn-sm btn-danger"
          >Vaciar Carro</a
        >
      </td>
    </tr>
    {% else %}
    <tr>
      <td colspan="3">
        <div class="alert alert-danger text-center">sin productos</div>
      </td>
    </tr>
    {% endif %}
  </tbody>

  <tfoot>
    <tr>
      <td colspan="3">
        <p style="color: white">Total: {{ importe_total_carro }} $</p>
      </td>
    </tr>
    {% if request.session.carro.items %}
    <tr class="text-center">
      <td colspan="3">
        <a href="../pedidos" class="btn btn-success">Realizar Pedido</a>
      </td>
    </tr>
    {% endif %}
  </tfoot>
</table>